# -*- coding: utf-8 -*-
"""Garbage detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orqivYEZIStq6GQkeco5tSztm9az3wRq
"""

!pip install ultralytics roboflow

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="HcWk84SEFo4kkBzvySj1")
project = rf.workspace("mini-project-zheci").project("garbage-segmentation-jr0aj")
version = project.version(1)
dataset = version.download("yolov8")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(data="/content/Garbage-Segmentation-1/data.yaml", epochs=50, imgsz=640)

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train5/weights/best.pt")
metrics=model.val()
metrics

from matplotlib import pyplot as plt

results = model.predict("/content/Garbage-Segmentation-1/test/images")

for r in results[:3]:
    plt.imshow(r.plot())
    plt.axis('off')
    plt.show()