apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-citizen
  namespace: cleanblr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-citizen
  template:
    metadata:
      labels:
        app: frontend-citizen
    spec:
      containers:
      - name: frontend-citizen
        image: adi7coder/cleanblr-frontend-citizen:latest
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-citizen
  namespace: cleanblr
spec:
  selector:
    app: frontend-citizen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-municipal
  namespace: cleanblr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-municipal
  template:
    metadata:
      labels:
        app: frontend-municipal
    spec:
      containers:
      - name: frontend-municipal
        image: adi7coder/cleanblr-frontend-municipal:latest
        ports:
        - containerPort: 5174
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-municipal
  namespace: cleanblr
spec:
  selector:
    app: frontend-municipal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5174
  type: LoadBalancer
